---
- name: Install Node Version Manager
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Ensure ansible bash environment exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-env.bashrc"
      register: ansible_env_bashrc

    - name: Ensure ansible env bashrc exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-env.bashrc"
        state: touch
      when: not ansible_env_bashrc.stat.exists

    - name: Put lines in bashrc from nvmsh
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-env.bashrc"
        line: export NVM_DIR="$XDG_DATA_HOME/nvm"

    - name: Source ansible env bashrc
      ansible.builtin.shell: source "{{ ansible_env.HOME }}/.bashrc"
      args:
        executable: /bin/bash

    - name: Ensure ansible nvmsh exist
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-nvmsh.bashrc"
      register: nvmsh_bashrc

    - name: Ensure ansible nvmsh bashrc exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-nvmsh.bashrc"
        state: touch
      when: not nvmsh_bashrc.stat.exists

    - name: Put lines in nvmsh bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-nvmsh.bashrc"
        line: |
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
