---
- name: Install Node Version Manager
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Check ansible bashrc file exist
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-env.bashrc"
      register: ansible_env_bashrc

    - name: Create ansible env bashrc if not exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-env.bashrc"
        state: touch
      when: not ansible_env_bashrc.stat.exists

    - name: Put lines in bashrc from nvmsh
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-env.bashrc"
        line: export NVM_DIR="$XDG_DATA_HOME/nvm"

    - name: Source ansible env bashrc
      ansible.builtin.shell: source "{{ ansible_env.HOME }}/.bashrc"
      args:
        executable: /bin/bash

    - name: Ensure ansible nvmsh exist
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-nvmsh.bashrc"
      register: nvmsh_bashrc

    - name: Ensure ansible nvmsh bashrc exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-nvmsh.bashrc"
        state: touch
      when: not nvmsh_bashrc.stat.exists

    - name: Put lines in nvmsh bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-nvmsh.bashrc"
        line: |
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

    - name: Create temporary empty directory
      ansible.builtin.file:
        path: "{{ ansible_env.XDG_DATA_HOME }}/nvm"
        state: directory
        mode: '0755'

    - name: Install nvm via git
      ansible.builtin.git:
        repo: 'https://github.com/nvm-sh/nvm.git'
        dest: "{{ ansible_env.XDG_DATA_HOME }}/nvm"
        version: v0.40.1

    - name: Source nvm script
      ansible.builtin.shell: source "{{ ansible_env.NVM_DIR }}/nvm.sh"
