---
- name: Install Node Version Manager
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Install nvm
      ansible.builtin.shell: >
        PROFILE=/dev/null bash -c curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
