---
- name: Install Dnf Packages
  hosts: localhost
  gather_facts: yes
  vars:
    base:
      - dmenu
      - i3
      - i3status
      - git
    terminalEmulator:
      - alacritty
      - gnome-terminal
    textEditor:
      - vim-enhanced
      - neovim
      - emacs-gtk+x11
    browser:
      - firefox
      - qutebrowser
      - chromium
    cliProgram:
      - cpu-x
      - lynx
      - redshift
    lightweightGUI:
      - zathura
      - zathura-plugins-all
    IDE:
      - geany
      - geany-themes
      - geany-plugins-autoclose
      - geany-plugins-vimode
      - geany-plugins-treebrowser
    GUI:
      - clementine
      - thunar
    language:
      - rustup
      - ruby
      - rbenv
    devops:
      - buildah
      - podman
      - python3
    pythonBased:
      - ansible
      - yamllint

  tasks:
    - name: Fedora Package
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ base }}"
        - "{{ textEditor }}"
        - "{{ terminalEmulator }}"
        - "{{ browser }}"
        - "{{ cliProgram }}"
        - "{{ lightweightGUI }}"
        - "{{ IDE }}"
        - "{{ GUI }}"
        - "{{ language }}"
        - "{{ devops }}"
        - "{{ pythonBased }}"
