---
- name: Install Dnf Packages
  hosts: localhost
  gather_facts: yes
  vars:
    base:
      - dmenu
      - i3
      - i3status
      - git
    terminal-emulator:
      - alacritty
      - gnome-terminal
    text-editor:
      - vim-enhanced
      - neovim
      - emacs-gtk+x11
    browser:
      - firefox
      - qutebrowser
      - chromium-browser
    cli-program:
      - cpu-x
      - lynx
      - redshift
    lightweight-GUI:
      - zathura
      - zathura-plugins-all
    IDE:
      - geany
      - geany-themes
      - geany-plugins-autoclose
      - geany-plugins-vimode
      - geany-plugins-treebrowser
    GUI:
      - clementine
      - thunar
    language:
      - rustup
      - ruby
      - rbenv
    devops:
      - buildah
      - podman
      - python3
    python-based:
      - ansible
      - yamllint

  tasks:
    - name: Fedora Package
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ base }}"
        - "{{ misc }}"
        - "{{ browser }}"
        - "{{ text-editor }}"
        - "{{ terminal-emulator }}"
        - "{{ IDE }}"
        - "{{ GUI }}"
        - "{{ language }}"
        - "{{ devops }}"
        - "{{ python-based }}"
        - "{{ generic }}"
