- name: Local install of golang
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Print go version
      ansible.builtin.debug: 
        var: go_version

    - name: Download latest stable version
      ansible.builtin.include_tasks:
        file: go-version.yaml
        apply:
          tags: go_version_download
        tags: always

    - name: Download source code with checksum (sha256)
      ansible.builtin.get_url:
        url: https://go.dev/dl/go{{ go_latest_stable_version }}.linux-amd64.tar.gz
        dest: "{{ ansible_env.HOME }}/Downloads"

    - name: Remove old golang install
      become: yes
      ansible.builtin.shell:
        cmd: "rm -rf /usr/local/go && tar -C /usr/local -xzf go{{ go_version }}.linux-amd64.tar.gz"
        chdir: "{{ ansible_env.HOME }}/Downloads"

    - name: Ensure export path environment variable is present
      ansible.builtin.lineinfile:
        state: present
        path: "{{ ansible_env.HOME }}/.bashrc.d/path.bashrc"
        line: export PATH=$PATH:/usr/local/go/bin

    - name: Source environment variable
      ansible.builtin.shell: source "{{ ansible_env.HOME }}/.bashrc"
      args:
        executable: /bin/bash

    - name: Check go command
      ansible.builtin.command:
        cmd: go version
      
      
