---
- name: Local install of golang
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Check current local installed go version
      ansible.builtin.command:
        cmd: go version
      register: go_command
      changed_when: go_command.rc != 0
      ignore_errors: true

    - name: No locally installed go
      ansible.builtin.import_tasks: no_local_installed_go.yaml
      when: go_command.rc != 0

    - name: Go local exists
      ansible.builtin.import_tasks: current_go_local_install.yaml
      when: go_command.rc == 0
