---
- name: Fedora Virtualization
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - name: Install virtualization pre-requisite dependencies
      ansible.builtin.dnf5:
        name: '@virtualization'
        state: present
        install_weak_deps: true

    - name: Start libvirt service on boot
      ansible.builtin.systemd_service:
        name: libvirtd
        enabled: true
        masked: false

    - name: Verify KVM kernel modules loaded
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          lsmod | grep "kvm"
      register: kvm
      changed_when: 'kvm.rc != 0'

    - name: Install podman
      ansible.builtin.dnf:
        name: 'podman'
        state: present
