---
- name: Flutter local install
  hosts: localhost
  gather_facts: yes
  vars_files:
    - ./vars/flutter-vars.yaml

  tasks:
    - name: Install fedora packages
      become: true
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ flutter.linux_package }}"

    - name: Create flutter directory on Downloads/ansible path
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Downloads/ansible/flutter"
        state: directory
        mode: '0755'

    - name: Check if zip file is already downloaded
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/Downloads/ansible/flutter/flutter_linux_{{ flutter.version }}-stable.tar.xz"
      register: flutter_sdk

    - name: Download flutter sdk
      ansible.builtin.get_url:
        url: "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_{{ flutter.version }}-stable.tar.xz"
        dest: "{{ ansible_env.HOME }}/Downloads/ansible/flutter"
        mode: '0644'
        timeout: 600
      when: not flutter_sdk.stat.exists

    - name: Check if file is already extracted
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.usr/share/flutter"
      register: flutter_dir

    - name: Extract zip file
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/Downloads/ansible/flutter/flutter_linux_{{ flutter.version }}-stable.tar.xz"
        dest: "{{ ansible_env.HOME }}/.usr/share"
      when: not flutter_dir.stat.exists
