---
- name: Create ansible environment variables for path and env
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Ensure Ansible ENV bashrc exist
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-env.bashrc"
      register: ansible_env_bashrc

    - name: Create Ansible ENV bashrc if not created
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-env.bashrc"
        state: touch
        mode: '0644'
      when: not ansible_env_bashrc.stat.exists

    - name: Ensure Ansible PATH bashrc exist
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-path.bashrc"
      register: ansible_path_bashrc

    - name: Create Ansible PATH bashrc if not created
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-path.bashrc"
        state: touch
        mode: '0644'
      when: not ansible_path_bashrc.stat.exists
