---
- hosts: localhost

  tasks:
    - name: Create directory for ansible directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Downloads/ansible"
        state: directory
        mode: '0755'
