---
- name: Create ansible directories
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Create directory for Downloads/ansible
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Downloads/ansible"
        state: directory
        mode: '0755'

    - name: Create directory for .usr/share
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.usr/share"
        state: directory
        mode: '0755'
