---
- name: Initialize util script
  hosts: localhosts
  gather_facts: true

- name: Include ansible directories
  ansible.builtin.import_playbook: ansible-directories.yaml

- name: Include ansible env variables
  ansible.builtin.import_playbook: ansible-env-variables.yaml
