---
- name: Initiate post install
  hosts: localhosts
  gather_facts: true

- name: Include go programs
  ansible.builtin.import_playbook: ./go-programs.yaml

- name: Include rust programs
  ansible.builtin.import_playbook: ./rust-programs.yaml

- name: Include vagrant
  ansible.builtin.import_playbook: ./vagrant.yaml
