---
- name: Install Rust Environment Variable
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Set rust environment variables
      ansible.builtin.blockinfile:
        append_newline: true
        prepend_newline: true
        marker: "# {mark} Rust"
        state: present
        path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-env.bashrc"
        block: |
          export RUSTUP_HOME="$HOME/.usr/rustup"
          export CARGO_HOME="$HOME/.usr/share/cargo"

    - name: Create cargo directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.usr/cargo"
        state: directory
        mode: '0755'

    - name: Create rustup directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.usr/rustup"
        state: directory
        mode: '0755'
