---
- name: Kubernetes kubectl Installation/Update
  hosts: localhost

  tasks:
    - name: Check if kubectl installer is already downloaded
      ansible.builtin.stat:
        path: "/tmp/kubectl"
      register: kubectl_installer

    - name: End play if kubectl is already installed at /tmp
      ansible.builtin.meta: end_play
      when: kubectl_installer.stat.exists

    - name: Get latest kubectl version
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: true
      register: kubectl_latest_version

    - name: Download latest kubectl
      ansible.builtin.uri:
        url: "https://dl.k8s.io/release/{{ kubectl_latest_version.content }}/bin/linux/amd64/kubectl"
        dest: "/tmp"
      when: not kubectl_installer.stat.exists

    - name: Check if kubectl checksum is already downloaded
      ansible.builtin.stat:
        path: "/tmp/kubectl.sha256"
      register: kubectl_installer_sha

    - name: Download kubectl checksum file
      ansible.builtin.uri:
        url: "https://dl.k8s.io/release/{{ kubectl_latest_version.content }}/bin/linux/amd64/kubectl.sha256"
        dest: "/tmp"
      when: not kubectl_installer_sha.stat.exists

    - name: Validate kubectl with checksum
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        chdir: "/tmp"
      register: kubectl_checksum_result
      changed_when: "kubectl_checksum_result.rc != 0"

    - name: Debug checksum result
      ansible.builtin.debug:
        var: kubectl_checksum_result

    - name: Check if kubectl is OK
      vars:
        expected: "kubectl: OK"
      ansible.builtin.assert:
        that:
          - kubectl_checksum_result.stdout == expected
        fail_msg: "kubectl failed"
        success_msg: "kubectl success"

    - name: Copy and make kubectl executable
      ansible.builtin.copy:
        src: /tmp/kubectl
        dest: "{{ ansible_env.HOME }}/.local/bin/kubectl"
        mode: +x

    - name: Check if kubectl is installed
      ansible.builtin.command: kubectl version --client --output=yaml
      register: kubectl_client
      changed_when: "kubectl_client.rc != 0"
