---
- name: Local install of Android Studio on Fedora
  hosts: localhost
  gather_facts: true
  vars:
    android_sdk_cli_version: 13114758
    android_fedora_packages:
      - zlib-ng.i686
      - ncurses-libs.i686
      - bzip2-libs.i686
  vars_files:
    - ../vars/vars_all.yaml

  tasks:
    - name: Create android directory on Downloads/ansible path
      ansible.builtin.file:
        path: "{{ ansible_installer_path }}/android"
        state: directory
        mode: '0755'

    - name: Create directory usr/share android
      ansible.builtin.file:
        path: "{{ ansible_user_path }}/android"
        state: directory
        mode: '0755'

    - name: Install required libraries for 64-bit machines fedora linux
      become: true
      ansible.builtin.dnf:
        name: "{{ android_fedora_packages }}"
        state: present
        update_cache: true

    - name: Check if zip file already downloaded
      ansible.builtin.stat:
        path: "{{ ansible_installer_path }}/android/commandlinetools-linux-{{ android_sdk_cli_version }}_latest.zip"
      register: android_zip_file

    - name: Download cli android sdk
      ansible.builtin.get_url:
        url: "https://dl.google.com/android/repository/commandlinetools-linux-{{ android_sdk_cli_version }}_latest.zip"
        dest: "{{ ansible_installer_path }}/android"
        mode: '0644'
      when: not android_zip_file.stat.exists

    - name: Check if android zip file is already extracted
      ansible.builtin.stat:
        path: "{{ ansible_user_path }}/cmdline-tools"
      register: android_cmdline_tools

    - name: Move directory and files
      ansible.builtin.unarchive:
        src: "{{ ansible_installer_path }}/android/commandlinetools-linux-{{ android_sdk_cli_version }}_latest.zip"
        dest: "{{ ansible_user_path }}/android"
      when: not android_cmdline_tools.stat.exists

    - name: Create directory for latest dir in cli
      ansible.builtin.file:
        path: "{{ ansible_user_path }}/android/cmdline-tools/latest"
        state: directory
        mode: '0755'

    - name: Check latest directory exists in usr/share/android
      ansible.builtin.stat:
        path: "{{ ansible_user_path }}/android/cmdline-tools/latest/bin"
      register: android_latest_dir

    - name: Move cli from current cmdline directory to latest directory
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "mv {{ ansible_user_path }}/android/cmdline-tools/bin {{ ansible_user_path }}/android/cmdline-tools/latest"
        - "mv {{ ansible_user_path }}/android/cmdline-tools/lib {{ ansible_user_path }}/android/cmdline-tools/latest"
        - "mv {{ ansible_user_path }}/android/cmdline-tools/NOTICE.txt {{ ansible_user_path }}/android/cmdline-tools/latest"
        - "mv {{ ansible_user_path }}/android/cmdline-tools/source.properties {{ ansible_user_path }}/android/cmdline-tools/latest"
      when: not android_latest_dir.stat.exists
      register: command_result
      changed_when: "command_result.rc != 0"

    - name: Check android sdkmanager
      ansible.builtin.command:
        cmd: sdkmanager --version
      register: sdkmanager_result
      changed_when: "sdkmanager_result.rc != 0"

    - name: Sdkmanager version
      ansible.builtin.debug:
        msg: "Android Sdkmanager Version is {{ sdkmanager_result.stdout }}"
