---
- name: Local install sdkman
  hosts: localhost
  vars_files:
    - ../vars/vars_all.yaml

  tasks:
    - name: Create ansible Download/ansible sdkman path
      ansible.builtin.file:
        path: "{{ ansible_installer_path }}/sdkman"
        state: directory
        mode: '0755'

    - name: Download sdkman script
      ansible.builtin.get_url:
        url: "https://get.sdkman.io?ci=true&rcupdate=false"
        dest: "{{ ansible_installer_path }}/sdkman/sdkman-install.sh"
        mode: '0755'

    - name: Execute sdkman shellscript
      ansible.builtin.command:
        cmd: "{{ ansible_installer_path }}/sdkman/sdkman-install.sh"
      register: sdkman_install
      changed_when: sdkman_install.rc != 0
