---
- hosts: localhost
  vars:
    fedora_packages:
      - zlib-ng.i686
      - ncurses-libs.i686
      - bzip2-libs.i686

  tasks:
    - name: Install required libraries for 64-bit machines fedora linux
      become: yes
      ansible.builtin.dnf:
        name: "{{ fedora_packages }}"
        state: present
        update_cache: yes

