---
- hosts: localhost

  tasks:
    - name: Check sdkmanager
      ansible.builtin.command:
        cmd: sdkmanager --version
      register: sdkmanager_result
      changed_when: "sdkmanager_result.rc != 0"

    - name: Sdkmanager version
      ansible.builtin.debug:
        msg: "version is {{ sdkmanager_result.stdout }}"
