---
- hosts: localhost

  tasks:
    - name: Include android path
      ansible.builtin.include_vars: ../var/android.yaml

    - name: Create directory
      ansible.builtin.file:
        path: "{{ android.path }}"
        state: directory
        mode: '0755'
