---
- hosts: localhost

  tasks:
    - name: Include android path
      ansible.builtin.include_vars: ../var/android.yaml

    - name: Check latest directory exists
      ansible.builtin.stat:
        path: "{{ android.path }}/cmdline-tools/latest"
      register: latest_dir

    - name: Move cli
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "mv {{ android.path }}/cmdline-tools/bin {{ android.path }}/cmdline-tools/latest"
        - "mv {{ android.path }}/cmdline-tools/lib {{ android.path }}/cmdline-tools/latest"
        - "mv {{ android.path }}/cmdline-tools/NOTICE.txt {{ android.path }}/cmdline-tools/latest"
        - "mv {{ android.path }}/cmdline-tools/source.properties {{ android.path }}/cmdline-tools/latest"
      when: not latest_dir.stat.exists
