---
- hosts: localhost

  tasks:
    - name: Get android variable
      ansible.builtin.include_vars: ../var/android.yaml

    - name: Move directory and files
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/Downloads/ansible/commandlinetools-linux-{{ android.sdk_cli_version }}_latest.zip"
        dest: "{{ android.path }}"
