---
- name: Install dnf packages
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: load variables
      ansible.builtin.include_vars:
        file: vars/packages.yaml
        name: packages
    - name: Package lists
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.generic }}"
          #  - "{{ lookup('file', 'packages.txt').splitlines() }}"
          #        "{{ lookup('file', 'clojure.txt').splitlines() }}"
