---
- hosts: localhost

  tasks:
    - name: Include android path
      ansible.builtin.include_vars: ../var/android.yaml

    - name: Create directory for latest dir in cli
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ android.path }}/cmdline-tools/latest"
        - "{{ android.path }}/cmdline-tools/latest"
