- name: Ensure ansible path executable exist in directoy
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-path-executable.bashrc"
  register: ansible_path_executable

- name: Create ansible path executable if not created
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-path-executable.bashrc"
    state: touch
  when: not ansible_path_executable.stat.exists
