- name: Ensure ansible path exist in directoy
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-path.bashrc"
  register: ansible_path

- name: Create ansible path if not created
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-path.bashrc"
    state: touch
  when: not ansible_path.stat.exists
