- name: Ensure ansible option exist in directoy
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-option.bashrc"
  register: ansible_option

- name: Create ansible option if not created
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-option.bashrc"
    state: touch
    mode: '0644'
  when: not ansible_option.stat.exists
