---
- hosts: localhost

  tasks:
    - name: Include android path
      ansible.builtin.include_vars: var.yaml

    - name: Create directory
      ansible.builtin.file:
        path: "{{ var.android_path }}"
        state: directory
        mode: '0755'
