---
- hosts: localhost

  tasks:
    - name: Include android path
      ansible.builtin.include_vars: var.yaml

    - name: Create directory for latest dir in cli
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ var.android_path }}/cmdline-tools/latest/bin"
        - "{{ var.android_path }}/cmdline-tools/latest/lib"
