---
- name: Flutter local install
  hosts: localhost
  gather_facts: yes
  vars:
    installer_path: "{{ ansible_env.HOME }}/Downloads/ansible/flutter"
    version: 3.32.0
    linux_package:
      - curl
      - git
      - unzip
      - xz
      - zip
      - mesa-libGLU

  tasks:
    - name: Install fedora packages
      become: true
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ linux_package }}"

    - name: Create flutter directory on Downloads/ansible path
      ansible.builtin.file:
        path: "{{ installer_path }}"
        state: directory
        mode: '0755'

    - name: Check if zip file is already downloaded
      ansible.builtin.stat:
        path: "{{ installer_path }}/flutter_linux_{{ version }}-stable.tar.xz"
      register: flutter_sdk

    - name: Download flutter sdk
      ansible.builtin.get_url:
        url: "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_{{ version }}-stable.tar.xz"
        dest: "{{ installer_path }}"
        mode: '0644'
        timeout: 600
      when: not flutter_sdk.stat.exists

    - name: Check if file is already extracted
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.usr/share/flutter"
      register: flutter_dir

    - name: Extract zip file
      ansible.builtin.unarchive:
        src: "{{ installer_path }}/flutter_linux_{{ version }}-stable.tar.xz"
        dest: "{{ ansible_env.HOME }}/.usr/share"
      when: not flutter_dir.stat.exists
