---
- name: Local clojure installation on Fedora Linux
  hosts: localhost
  gather_facts: true
  vars:
    dependencies:
      - bash
      - curl
      - java-latest-openjdk
      - rlwrap

  tasks:
    - name: Check pre-requisites dependencies
      become: true
      ansible.builtin.dnf:
        name: "{{ dependencies }}"
        state: present
        update_cache: true

    - name: Check if installer script exist locally
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/Downloads/linux-install.sh"
      register: clojure_installer_script

    - name: Download linux script installer
      ansible.builtin.get_url:
        url: "https://github.com/clojure/brew-install/\
          releases/latest/download/linux-install.sh"
        dest: "{{ ansible_env.HOME }}/Downloads"
        mode: "0755"
      when: not clojure_installer_script.stat.exists

    - name: Create custom directory on /opt if it does not exist
      become: true
      ansible.builtin.file:
        path: /opt/infrastructure/clojure
        state: directory
        mode: '0755'

    - name: Clojure exist in package dnf
      ansible.builtin.package_facts:
        manager: "dnf"
      register: packages_dnf

    - name: Execute script
      become: true
      ansible.builtin.script:
        cmd: >
          {{ ansible_env.HOME }}/Downloads/linux-install.sh
          --prefix /opt/infrastructure/clojure
      when: "'clojure' in packages_dnf"

    - name: Extend the MANPATH to include on manual pages
      become: true
      ansible.builtin.lineinfile:
        path: /etc/man_db.conf
        line: >
          MANPATH_MAP /opt/infrastructure/clojure/bin
          /opt/infrastructure/clojure/man

    - import_tasks: shared/ansible_path_executable.yml

    - name: Ensure clojure optional directory is on PATH environment
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc.d/\
          ansible-path-executable.bashrc"
        line: export PATH="/opt/infrastructure/clojure/bin:$PATH" 
