---
- name: Local minikube RPM package installation x86-64 Stable branch
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Create bash env if not found
      ansible.builtin.import_tasks:
        file: ./shared/ansible_path.yml

    - name: Set environment variable
      ansible.builtin.lineinfile:
        state: present
        path: "{{ ansible_env.HOME }}/.bashrc.d/ansible-path.bashrc"
        line: "export MINIKUBE_HOME={{ ansible_env.HOME }}/opt/minikube"

    - name: Create minikube directory in /opt
      become: true
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/opt/minikube"
        state: directory
        mode: '0755'

    - name: Check if rpm installer already exist
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/Downloads/ansible/minikube-latest.x86_64.rpm"
      register: minikube_rpm

    - name: Download remote install script
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
        dest: "{{ ansible_env.HOME }}/Downloads/ansible"
        mode: '0644'
      when: not minikube_rpm.stat.exists

    - name: Install rpm package with user privileged
      become: true
      ansible.builtin.script:
        cmd: /usr/bin/rpm -Uvh "{{ ansible_env.HOME }}/Downloads/ansible/minikube-latest.x86_64.rpm"
