---
- name: Local minikube RPM package installation x86-64 Stable branch
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Set environment variable
      ansible.builtin.lineinfile:
        state: present
        path: "{{ ansible_env.HOME }}/.bashrc.d/env.bashrc"
        line: export MINIKUBE_HOME=$XDG_CONFIG_HOME/minikube

    - name: Download remote install script
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
        dest: "{{ ansible_env.HOME }}"

    - name: Download fedora virtualization
      ansible.builtin.dnf:
        name: "@virtualization"
