---
- name: Foo
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Create foo if bar not found
      ansible.builtin.import_tasks:
        file: ./foo/bar.yml

    - name: Check if foo already exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/foo.tar.gz }}"
      register: foo_bar
