---
- name: Install Clojure Environment Variable
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Set clojure environment path
      ansible.builtin.blockinfile:
        append_newline: true
        prepend_newline: true
        marker: "# {mark} Clojure"
        state: present
        path: "{{ ansible_env.HOME }}/DevOps/.bashrc.d/path.bashrc"
        block: |
          export PATH="$PATH:${HOME}/DevOps/opt/infrastructure/clojure/bin"
