---
- name: Install Go Environment Variable
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Set go environment variables
      ansible.builtin.blockinfile:
        append_newline: true
        prepend_newline: true
        marker: "# {mark} Go"
        state: present
        path: "{{ ansible_env.HOME }}/DevOps/bashrc.d/env.bashrc"
        block: |
          export GOPATH="$HOME/DevOps/proglang/go"

    - name: Set go environment path
      ansible.builtin.blockinfile:
        append_newline: true
        prepend_newline: true
        marker: "# {mark} Go"
        state: present
        path: "{{ ansible_env.HOME }}/DevOps/bashrc.d/path.bashrc"
        block: |
          export PATH="$PATH:/usr/local/go/bin"
          export PATH="$PATH:$HOME/DevOps/proglang/go/bin"
