---
- name: Local install of Android Studio on Fedoraa
  hosts: localhost
  gather_facts: yes
  vars:
    fedora_packages:
      - zlib-ng.i686
      - ncurses-libs.i686
      - bzip2-libs.i686

  tasks: 
    - name: Print fedora packages
      ansible.builtin.debug:
        var: fedora_packages

    - name: Installation of required libraries for 64-bit machines on fedora
      become: yes
      ansible.builtin.dnf:
        name: "{{ fedora_packages }}"
        state: present
        update_cache: yes

    - name: Creadte directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Android/Sdk"
        state: directory
        mode: '0755'

    - name: Set environment variable
      ansible.builtin.lineinfile:
        state: present
        path: "{{ ansible_env.HOME }}/.bashrc.d/path.bashrc"
        line: "{{ item }}"
      loop:
        - export ANDROID_HOME=$HOME/Android/Sdk
        - export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
        - export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

    - name: Download cli android
      ansible.builtin.unarchive:
        remote_src: yes
        src: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        dest: "{{ ansible_env.HOME }}/Android/Sdk"

    - name: Source environment variable
      ansible.builtin.shell: source "{{ ansible_env.HOME }}/.bashrc"
      args:
        executable: /bin/bash
