- name: Flutter local install
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: gather
      ansible.builtin.include_tasks:
        file: gather-info.yaml

    - name: Check installed tools
      vars:
        package:
        - bash
        - file
        - mkdir
        - rm 
        - which
      ansible.builtin.shell:
        cmd: "which {{ item }}"
      loop: "{{ package }}"
      tags:
      - check_install

    - name: gather package facts
      ansible.builtin.package_facts:
        manager: auto
      tags:
      - package_facts

    - name: Install pre-requisite packages
      become: true
      tags: pre_package
      vars:
        package:
        - curl
        - git
        - unzip
        - xz
        - zip
        - mesa-libGLU
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ package }}"
    
    - name: Install pre-requisite for flutter desktop
      ansible.builtin.include_tasks:
        file: linux-desktop.yaml 
        apply:
          tags: desktop
      tags: always

    - name: Include flutter stable latest version
      ansible.builtin.include_vars:
        file: flutter-version.yaml
        name: flutter_version
        
    - debug:
        var: flutter_version

    - debug:
        var: "{{ ansible_env.HOME}}/Downloads"
      tags: test

    - name: Consider /usr/bin exist to put the binary
      ansible.builtin.stat:
        path: /usr/bin
      register: p

    - name: Check if path exist
      ansible.builtin.debug:
        msg: "Path {{ p }} exist and a directory"
      when: p.stat.isdir is defined and p.stat.isdir

    - name: Extract SDK
      become: yes
      ansible.builtin.unarchive:
        remote_src: yes
        src: "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_{{ flutter_version.version }}-stable.tar.xz"
        dest: /usr/bin

    - name: Ensure flutter path exist on PATH environment
      ansible.builtin.lineinfile:
        state: present
        path: "{{ ansible_env.HOME }}/.bashrc.d/path.bashrc"
        line: export PATH=/usr/bin/flutter/bin:$PATH

    - name: Source environment variable
      ansible.builtin.shell: source "{{ ansible_env.HOME }}/.bashrc" && flutter --version
      args:
        executable: /bin/bash
