- name: test
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: gather
      ansible.builtin.include_tasks:
        file: gather-info.yaml

    - name: Check installed tools
      vars:
        package:
        - bash
        - file
        - mkdir
        - rm 
        - which
      ansible.builtin.shell:
        cmd: "which {{ item }}"
      loop: "{{ package }}"
      tags:
      - check_install

    - name: gather package facts
      ansible.builtin.package_facts:
        manager: auto
      tags:
      - package_facts

    - name: Install pre-requisite packages
      become: true
      tags: pre_package
      vars:
        package:
        - curl
        - git
        - unzip
        - xz
        - zip
        - mesa-libGLU
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ package }}"
    
    - name: Install pre-requisite for flutter desktop
      ansible.builtin.include_tasks:
        file: linux-desktop.yaml 
        apply:
          tags: desktop
      tags: always
