---
- name: Install dnf packages
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: load variables
      ansible.builtin.include_vars:
        dir: vars
        name: packages
    - name: Package lists
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ packages.generic }}"
        - "{{ packages.clojure }}"
