---
# tasks file for fedora-dev-env
---
- name: Install Node Version Manager
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Install nvm
      ansible.builtin.shell: >
        PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash'
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install dnf packages
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: load variables
      ansible.builtin.include_vars:
        dir: vars
        name: packages
    - name: Package lists
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ packages.generic }}"
        - "{{ packages.clojure }}"
