---
- name: Local install sdkman
  hosts: localhost

  tasks:
    # - name: Check Sdkman directory
    #   ansible.builtin.stat:
    #     path: "{{ ansible_env.HOME }}/DevOps/sdk/sdkman"
    #   register: sdkman_directory

    # - name: Create Sdkman directory
    #   ansible.builtin.file:
    #     path: "{{ ansible_env.HOME }}/DevOps/sdk/sdkman"
    #     state: directory
    #     mode: '0755'
    #   when: not sdkman_directory.stat.exists

    - name: Install sdkman CI mode non-interactive use
      ansible.builtin.get_url:
        url: "https://get.sdkman.io?ci=true&rcupdate=false"
        dest: /tmp/sdkman-install.sh
        mode: '0755'

    - name: Execute sdkman shellscript
      ansible.builtin.command:
        cmd: /tmp/sdkman-install.sh
      register: sdkman_install
      changed_when: sdkman_install.rc != 0
