---
- name: Set android environment variable
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Set android environment variable
      ansible.builtin.blockinfile:
        append_newline: true
        prepend_newline: true
        marker: "# {mark} Android"
        state: present
        path: "{{ ansible_env.HOME }}/DevOps/bashrc.d/env.bashrc"
        block: |
          export ANDROID_HOME="$HOME/DevOps/sdk/android"
          export ANDROID_USER_HOME="$HOME/DevOps/sdk/android"

    - name: Set android environment path
      ansible.builtin.blockinfile:
        append_newline: true
        prepend_newline: true
        marker: "# {mark} Android"
        state: present
        path: "{{ ansible_env.HOME }}/DevOps/bashrc.d/path.bashrc"
        block: |
          export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin"
          export PATH="$PATH:$ANDROID_HOME/tools"
          export PATH="$PATH:$ANDROID_HOME/tools/bin"
          export PATH="$PATH:$ANDROID_HOME/platform-tools"
