---
- name: Local clojure installation on Fedora Linux
  hosts: localhost
  gather_facts: true
  vars:
    installer_path: "{{ ansible_env.HOME }}/Downloads/ansible/clojure"
    dependencies:
      - bash
      - curl
      - java-latest-openjdk
      - rlwrap

  tasks:
    - name: Create clojure directory installer path
      ansible.builtin.file:
        path: "{{ installer_path }}"
        state: directory
        mode: '0755'

    - name: Check pre-requisites dependencies in linux
      become: true
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ dependencies }}"

    - name: Check if installer script exist locally
      ansible.builtin.stat:
        path: "{{ installer_path }}/linux-install.sh"
      register: clojure_installer_script

    - name: Download linux script installer
      ansible.builtin.get_url:
        url: "https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh"
        dest: "{{ installer_path }}"
        mode: "0755"
      when: not clojure_installer_script.stat.exists

    - name: Create custom directory on /opt if it does not exist
      become: true
      ansible.builtin.file:
        path: /opt/infrastructure/clojure
        state: directory
        mode: '0755'

    - name: Clojure exist in package dnf
      ansible.builtin.command: clojure --version
      register: clojure_program
      changed_when: "clojure_program.rc != 0"

    - name: Execute script
      become: true
      ansible.builtin.command: "{{ installer_path }}/linux-install.sh --prefix /opt/infrastructure/clojure"
      register: clojure_program
      when: "clojure_program.rc != 0"

    - name: Extend the MANPATH to include on manual pages
      become: true
      ansible.builtin.lineinfile:
        path: /etc/man_db.conf
        line: MANPATH_MAP /opt/infrastructure/clojure/bin /opt/infrastructure/clojure/man
