---
- name: Install Node Version Manager
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars_all.yaml

  tasks:
    - name: Create usr/share/nvm/bin directory
      ansible.builtin.file:
        path: "{{ ansible_user_path }}/nvm/bin"
        state: directory
        mode: '0755'

    - name: Install nvm script
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash'
      register: nvm_result
      changed_when: 'nvm_result.rc != 0'
