---
- name: Initialize util script
  hosts: localhosts
  gather_facts: true

- name: Include util main
  ansible.builtin.import_playbook: ./util/main.yaml

- name: Include env main
  ansible.builtin.import_playbook: ./env/main.yaml
